baseURL = 'https://enric0r.github.io/choco.github.io/'
languageCode = 'en'
title = 'ChoCo — USB MIDI chord controller'
disableKinds = ['taxonomy', 'term', 'RSS']

[markup.goldmark.renderer]
  unsafe = false
