[[main]]
    name = "Docs"
    pageRef = "docs"
    weight = 10

[[main]]
    name = "About"
    pageRef = "about"
    weight = 20

[[main]]
    pre = "github"
    name = ""
    url = "https://github.com/enric0r/ChoCo"
    weight = 30